#ifndef EXECWAKE_BPF_PROTOCOL_H
#define EXECWAKE_BPF_PROTOCOL_H

typedef unsigned char __u8;
typedef unsigned short __u16;
typedef unsigned int __u32;
typedef unsigned long long __u64;
typedef int __s32;
typedef long long __s64;

enum execwake_event_kind {
    EXECWAKE_EVENT_HEARTBEAT = 0,
    EXECWAKE_EVENT_PROCESS_FORK = 1,
    EXECWAKE_EVENT_PROCESS_EXEC = 2,
    EXECWAKE_EVENT_PROCESS_EXIT = 3,
    EXECWAKE_EVENT_SYSCALL = 4,
};

enum execwake_syscall_operation {
    EXECWAKE_SYSCALL_SOCKET = 1,
    EXECWAKE_SYSCALL_BIND = 2,
    EXECWAKE_SYSCALL_CONNECT = 3,
    EXECWAKE_SYSCALL_LISTEN = 4,
    EXECWAKE_SYSCALL_ACCEPT = 5,
    EXECWAKE_SYSCALL_CLOSE = 6,
    EXECWAKE_SYSCALL_DUP = 7,
    EXECWAKE_SYSCALL_FCNTL = 8,
    EXECWAKE_SYSCALL_SENDTO = 9,
    EXECWAKE_SYSCALL_RECVFROM = 10,
    EXECWAKE_SYSCALL_WRITE = 11,
    EXECWAKE_SYSCALL_READ = 12,
    EXECWAKE_SYSCALL_OPEN_AT = 13,
    EXECWAKE_SYSCALL_READ_VECTOR = 14,
    EXECWAKE_SYSCALL_WRITE_VECTOR = 15,
    EXECWAKE_SYSCALL_READ_AT = 16,
    EXECWAKE_SYSCALL_WRITE_AT = 17,
    EXECWAKE_SYSCALL_TRUNCATE = 18,
    EXECWAKE_SYSCALL_FILE_TRUNCATE = 19,
    EXECWAKE_SYSCALL_RENAME_AT = 20,
    EXECWAKE_SYSCALL_LINK_AT = 21,
    EXECWAKE_SYSCALL_SYMLINK_AT = 22,
    EXECWAKE_SYSCALL_UNLINK_AT = 23,
    EXECWAKE_SYSCALL_MAKE_DIRECTORY_AT = 24,
    EXECWAKE_SYSCALL_CHANGE_DIRECTORY = 25,
    EXECWAKE_SYSCALL_CHANGE_DIRECTORY_FD = 26,
    EXECWAKE_SYSCALL_MEMORY_MAP = 27,
    EXECWAKE_SYSCALL_STAT_AT = 28,
    EXECWAKE_SYSCALL_READ_LINK_AT = 29,
    EXECWAKE_SYSCALL_READ_DIRECTORY = 30,
    EXECWAKE_SYSCALL_OPEN = 31,
    EXECWAKE_SYSCALL_CREATE = 32,
    EXECWAKE_SYSCALL_RENAME = 33,
    EXECWAKE_SYSCALL_LINK = 34,
    EXECWAKE_SYSCALL_SYMLINK = 35,
    EXECWAKE_SYSCALL_UNLINK = 36,
    EXECWAKE_SYSCALL_MAKE_DIRECTORY = 37,
    EXECWAKE_SYSCALL_REMOVE_DIRECTORY = 38,
    EXECWAKE_SYSCALL_STAT = 39,
    EXECWAKE_SYSCALL_OPEN_AT_2 = 40,
    EXECWAKE_SYSCALL_CLONE = 41,
    EXECWAKE_SYSCALL_CLONE_3 = 42,
    EXECWAKE_SYSCALL_FORK = 43,
    EXECWAKE_SYSCALL_GET_SOCKET_NAME = 44,
    EXECWAKE_SYSCALL_GET_PEER_NAME = 45,
};

enum {
    EXECWAKE_PROTOCOL_VERSION = 1,
    EXECWAKE_EVENT_DATA_BYTES = 384,
    EXECWAKE_SOCKET_ADDRESS_BYTES = 128,
    EXECWAKE_SOCKET_PAYLOAD_BYTES = 248,
    EXECWAKE_SYSCALL_OPERATION_MASK = 0xffff,
    EXECWAKE_DATA_HAS_ADDRESS = 1 << 16,
    EXECWAKE_DATA_HAS_PAYLOAD = 1 << 17,
    EXECWAKE_DATA_TRUNCATED = 1 << 18,
    EXECWAKE_DATA_HAS_FIRST_PATH = 1 << 19,
    EXECWAKE_DATA_HAS_SECOND_PATH = 1 << 20,
    EXECWAKE_PATH_BYTES = 188,
};

#define EXECWAKE_RESULT_UNKNOWN (-9223372036854775807LL - 1)

struct execwake_event_header {
    __u16 version;
    __u16 kind;
    __u32 size;
    __u64 monotonic_ns;
    __u32 tgid;
    __u32 tid;
    __s64 result;
    __u64 arguments[6];
    __u32 data_length;
    __u32 flags;
};

struct execwake_event {
    struct execwake_event_header header;
    __u8 data[EXECWAKE_EVENT_DATA_BYTES];
};

struct execwake_socket_data {
    __u32 address_length;
    __u32 payload_length;
    __u8 address[EXECWAKE_SOCKET_ADDRESS_BYTES];
    __u8 payload[EXECWAKE_SOCKET_PAYLOAD_BYTES];
};

struct execwake_path_data {
    __u32 first_length;
    __u32 second_length;
    __u8 first[EXECWAKE_PATH_BYTES];
    __u8 second[EXECWAKE_PATH_BYTES];
};

_Static_assert(sizeof(struct execwake_event_header) == 88,
               "unexpected event header size");
_Static_assert(sizeof(struct execwake_event) == 472,
               "unexpected event size");

#endif
